# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-vFkFY6XYHwg4-dxgIW3tWwZ-9cSlk2
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df=pd.read_csv('ai_impact_student_performance_dataset.csv')
df.head()

# Check missing values
print(df.isnull().sum())

# Fill numerical missing values with mean
df.fillna(df.mean(numeric_only=True), inplace=True)

# Fill categorical missing values with mode
for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0], inplace=True)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Example column
df['gender'] = le.fit_transform(df['gender'])

print(df['gender'].head())

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(), ['grade_level'])
    ],
    remainder='passthrough'
)

df_encoded = ct.fit_transform(df)
print(df_encoded)

# Example target column
X = df.drop(['final_score'], axis=1)
y = df['final_score']

import matplotlib.pyplot as plt
import seaborn as sns

# Correlation heatmap
plt.figure()
sns.heatmap(df.corr(), annot=False)
plt.show()

# Distribution
df['final_score'].hist()
plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_reg, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, pred))

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_clf, test_size=0.2)

clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# SVM
svm = SVC()
svm.fit(X_train, y_train)

# KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

importances = clf.feature_importances_
feature_names = X.columns

for name, val in zip(feature_names, importances):
    print(name, val)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # for classification
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_scaled, y_clf, epochs=10, batch_size=32)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3)
clusters = kmeans.fit_predict(X_scaled)

df['cluster'] = clusters

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

print(classification_report(y_test, pred))

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', RandomForestClassifier())
])

pipeline.fit(X, y_clf)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y_clf,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y_reg,
    test_size=0.2,
    random_state=42
)

